# Generated by Django 5.1.5 on 2025-06-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_profile_twitter_access_token_and_more'),
    ]

    operations = [
    ]
